// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vizsga3.Models;

#nullable disable

namespace vizsga3.Migrations
{
    [DbContext(typeof(Vizsga3Context))]
    [Migration("20250227084403_AddKategoriaToKartyak")]
    partial class AddKategoriaToKartyak
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Kartyak", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(255)")
                        .HasColumnName("id");

                    b.Property<int?>("price")
                        .HasColumnType("int(255)")
                        .HasColumnName("ar");

                    b.Property<string>("CurrentUser")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nev");

                    b.Property<string>("image")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("kep_url");

                    b.Property<string>("description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("leiras");

                    b.HasKey("id")
                        .HasName("PRIMARY");

                    b.ToTable("kartyak", (string)null);
                });

            modelBuilder.Entity("vizsga3.Models.Felhasznalok", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(255)")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("felhasznalonev");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("jelszo");

                    b.HasKey("id")
                        .HasName("PRIMARY");

                    b.ToTable("felhasznalok", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
